language: bash
sudo: required
services:
  - docker
before_install:
  - docker pull library/nginx:stable-alpine
before_script:
  - sudo apt-get update && sudo apt-get install git
script:
  - make
after_success:
  - make push_image
env:
  global:
